SET SQL DIALECT 3; 

CREATE DATABASE 'BASE.FDB' PAGE_SIZE 4096 DEFAULT CHARACTER SET UTF8;


/*  Generators or sequences */
CREATE GENERATOR AUDIENCES_GEN;
CREATE GENERATOR GROUPS_GEN;
CREATE GENERATOR LESSONS_GEN;
CREATE GENERATOR LESSON_TYPES_GEN;
CREATE GENERATOR SCHED_ITEMS_GEN;
CREATE GENERATOR SUBJECTS_GEN;
CREATE GENERATOR TEACHERS_GEN;

COMMIT WORK;

/* Table: AUDIENCES, Owner: SYSDBA */
CREATE TABLE AUDIENCES (ID INTEGER NOT NULL,
        NAME VARCHAR(64),
PRIMARY KEY (ID));

/* Table: GROUPS, Owner: SYSDBA */
CREATE TABLE GROUPS (ID INTEGER NOT NULL,
        NAME VARCHAR(64),
PRIMARY KEY (ID));

/* Table: LESSONS, Owner: SYSDBA */
CREATE TABLE LESSONS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
        ORDER_NUMBER INTEGER,
PRIMARY KEY (ID),
CONSTRAINT UNIQ_LESSON_ORDER UNIQUE (ORDER_NUMBER));

/* Table: LESSON_TYPES, Owner: SYSDBA */
CREATE TABLE LESSON_TYPES (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: SCHED_ITEMS, Owner: SYSDBA */
CREATE TABLE SCHED_ITEMS (ID INTEGER NOT NULL,
        LESSON_ID INTEGER,
        SUBJECT_ID INTEGER,
        AUDIENCE_ID INTEGER,
        GROUP_ID INTEGER,
        TEACHER_ID INTEGER,
        TYPE_ID INTEGER,
        WEEKDAY_ID INTEGER,
PRIMARY KEY (ID));

/* Table: SUBJECTS, Owner: SYSDBA */
CREATE TABLE SUBJECTS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: SUBJECT_GROUP, Owner: SYSDBA */
CREATE TABLE SUBJECT_GROUP (SUBJECT_ID INTEGER NOT NULL,
        GROUP_ID INTEGER NOT NULL,
CONSTRAINT UNIQ_SUBJECTID_GROUPID UNIQUE (SUBJECT_ID, GROUP_ID));

/* Table: SUBJECT_TEACHER, Owner: SYSDBA */
CREATE TABLE SUBJECT_TEACHER (SUBJECT_ID INTEGER NOT NULL,
        TEACHER_ID INTEGER NOT NULL,
CONSTRAINT UNIQ_SUBJECTID_TEACHERID UNIQUE (SUBJECT_ID, TEACHER_ID));

/* Table: TEACHERS, Owner: SYSDBA */
CREATE TABLE TEACHERS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: WEEKDAYS, Owner: SYSDBA */
CREATE TABLE WEEKDAYS (ID INTEGER NOT NULL,
        NAME VARCHAR(64) NOT NULL,
        ORDER_NUMBER INTEGER NOT NULL,
PRIMARY KEY (ID),
UNIQUE (ORDER_NUMBER));

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_1 FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_2 FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_3 FOREIGN KEY (AUDIENCE_ID) REFERENCES AUDIENCES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_4 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_5 FOREIGN KEY (TYPE_ID) REFERENCES LESSON_TYPES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_6 FOREIGN KEY (WEEKDAY_ID) REFERENCES WEEKDAYS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_7 FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SUBJECT_TEACHER ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_TEACHER ADD FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER AUDIENCES_AUTOINC_ID FOR AUDIENCES 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (AUDIENCES_GEN, 1);
END ^

CREATE TRIGGER GROUPS_AUTOINC_ID FOR GROUPS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (GROUPS_GEN, 1);
END ^

CREATE TRIGGER LESSONS_AUTOINC_ID FOR LESSONS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSONS_GEN, 1);
END ^

CREATE TRIGGER LESSON_TYPES_AUTOINC_ID FOR LESSON_TYPES 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSON_TYPES_GEN, 1);
END ^

CREATE TRIGGER SCHED_ITEMS_AUTOINC_ID FOR SCHED_ITEMS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(SCHED_ITEMS_GEN, 1);
END ^

CREATE TRIGGER SUBJECT_AUTOINC_ID FOR SUBJECTS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(subjects_gen, 1);
END ^

CREATE TRIGGER TEACHERS_AUTOINC_ID FOR TEACHERS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (TEACHERS_GEN, 1);
END ^


SET TERM ; ^
COMMIT WORK;

SET SQL DIALECT 3; 

/* CREATE DATABASE 'C:\Users\Lenovo\PycharmProjects\wba\BASE.FDB' PAGE_SIZE 4096 DEFAULT CHARACTER SET UTF8; */


/*  Generators or sequences */
CREATE GENERATOR AUDIENCES_GEN;
CREATE GENERATOR GROUPS_GEN;
CREATE GENERATOR LESSONS_GEN;
CREATE GENERATOR LESSON_TYPES_GEN;
CREATE GENERATOR SCHED_ITEMS_GEN;
CREATE GENERATOR SUBJECTS_GEN;
CREATE GENERATOR TEACHERS_GEN;

COMMIT WORK;

/* Table: AUDIENCES, Owner: SYSDBA */
CREATE TABLE AUDIENCES (ID INTEGER NOT NULL,
        NAME VARCHAR(64),
PRIMARY KEY (ID));

/* Table: GROUPS, Owner: SYSDBA */
CREATE TABLE GROUPS (ID INTEGER NOT NULL,
        NAME VARCHAR(64),
PRIMARY KEY (ID));

/* Table: LESSONS, Owner: SYSDBA */
CREATE TABLE LESSONS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
        ORDER_NUMBER INTEGER,
PRIMARY KEY (ID),
CONSTRAINT UNIQ_LESSON_ORDER UNIQUE (ORDER_NUMBER));

/* Table: LESSON_TYPES, Owner: SYSDBA */
CREATE TABLE LESSON_TYPES (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: SCHED_ITEMS, Owner: SYSDBA */
CREATE TABLE SCHED_ITEMS (ID INTEGER NOT NULL,
        LESSON_ID INTEGER,
        SUBJECT_ID INTEGER,
        AUDIENCE_ID INTEGER,
        GROUP_ID INTEGER,
        TEACHER_ID INTEGER,
        TYPE_ID INTEGER,
        WEEKDAY_ID INTEGER,
PRIMARY KEY (ID));

/* Table: SUBJECTS, Owner: SYSDBA */
CREATE TABLE SUBJECTS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: SUBJECT_GROUP, Owner: SYSDBA */
CREATE TABLE SUBJECT_GROUP (SUBJECT_ID INTEGER NOT NULL,
        GROUP_ID INTEGER NOT NULL,
CONSTRAINT UNIQ_SUBJECTID_GROUPID UNIQUE (SUBJECT_ID, GROUP_ID));

/* Table: SUBJECT_TEACHER, Owner: SYSDBA */
CREATE TABLE SUBJECT_TEACHER (SUBJECT_ID INTEGER NOT NULL,
        TEACHER_ID INTEGER NOT NULL,
CONSTRAINT UNIQ_SUBJECTID_TEACHERID UNIQUE (SUBJECT_ID, TEACHER_ID));

/* Table: TEACHERS, Owner: SYSDBA */
CREATE TABLE TEACHERS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: WEEKDAYS, Owner: SYSDBA */
CREATE TABLE WEEKDAYS (ID INTEGER NOT NULL,
        NAME VARCHAR(64) NOT NULL,
        ORDER_NUMBER INTEGER NOT NULL,
PRIMARY KEY (ID),
UNIQUE (ORDER_NUMBER));

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_1 FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_2 FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_3 FOREIGN KEY (AUDIENCE_ID) REFERENCES AUDIENCES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_4 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_5 FOREIGN KEY (TYPE_ID) REFERENCES LESSON_TYPES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_6 FOREIGN KEY (WEEKDAY_ID) REFERENCES WEEKDAYS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_7 FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SUBJECT_TEACHER ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_TEACHER ADD FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER AUDIENCES_AUTOINC_ID FOR AUDIENCES 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (AUDIENCES_GEN, 1);
END ^

CREATE TRIGGER GROUPS_AUTOINC_ID FOR GROUPS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (GROUPS_GEN, 1);
END ^

CREATE TRIGGER LESSONS_AUTOINC_ID FOR LESSONS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSONS_GEN, 1);
END ^

CREATE TRIGGER LESSON_TYPES_AUTOINC_ID FOR LESSON_TYPES 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSON_TYPES_GEN, 1);
END ^

CREATE TRIGGER SCHED_ITEMS_AUTOINC_ID FOR SCHED_ITEMS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(SCHED_ITEMS_GEN, 1);
END ^

CREATE TRIGGER SUBJECT_AUTOINC_ID FOR SUBJECTS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(subjects_gen, 1);
END ^

CREATE TRIGGER TEACHERS_AUTOINC_ID FOR TEACHERS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (TEACHERS_GEN, 1);
END ^


SET TERM ; ^
COMMIT WORK;

SET SQL DIALECT 3; 

/* CREATE DATABASE 'C:\Users\Lenovo\Downloads\fbexport-1.90\fbexport-1.90\exe\BASE.FDB' PAGE_SIZE 4096 DEFAULT CHARACTER SET UTF8; */


/*  Generators or sequences */
CREATE GENERATOR AUDIENCES_GEN;
CREATE GENERATOR GROUPS_GEN;
CREATE GENERATOR LESSONS_GEN;
CREATE GENERATOR LESSON_TYPES_GEN;
CREATE GENERATOR SCHED_ITEMS_GEN;
CREATE GENERATOR SUBJECTS_GEN;
CREATE GENERATOR TEACHERS_GEN;

COMMIT WORK;

/* Table: AUDIENCES, Owner: SYSDBA */
CREATE TABLE AUDIENCES (ID INTEGER NOT NULL,
        NAME VARCHAR(64),
PRIMARY KEY (ID));

/* Table: GROUPS, Owner: SYSDBA */
CREATE TABLE GROUPS (ID INTEGER NOT NULL,
        NAME VARCHAR(64),
PRIMARY KEY (ID));

/* Table: LESSONS, Owner: SYSDBA */
CREATE TABLE LESSONS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
        ORDER_NUMBER INTEGER,
PRIMARY KEY (ID),
CONSTRAINT UNIQ_LESSON_ORDER UNIQUE (ORDER_NUMBER));

/* Table: LESSON_TYPES, Owner: SYSDBA */
CREATE TABLE LESSON_TYPES (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: SCHED_ITEMS, Owner: SYSDBA */
CREATE TABLE SCHED_ITEMS (ID INTEGER NOT NULL,
        LESSON_ID INTEGER,
        SUBJECT_ID INTEGER,
        AUDIENCE_ID INTEGER,
        GROUP_ID INTEGER,
        TEACHER_ID INTEGER,
        TYPE_ID INTEGER,
        WEEKDAY_ID INTEGER,
PRIMARY KEY (ID));

/* Table: SUBJECTS, Owner: SYSDBA */
CREATE TABLE SUBJECTS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: SUBJECT_GROUP, Owner: SYSDBA */
CREATE TABLE SUBJECT_GROUP (SUBJECT_ID INTEGER NOT NULL,
        GROUP_ID INTEGER NOT NULL,
CONSTRAINT UNIQ_SUBJECTID_GROUPID UNIQUE (SUBJECT_ID, GROUP_ID));

/* Table: SUBJECT_TEACHER, Owner: SYSDBA */
CREATE TABLE SUBJECT_TEACHER (SUBJECT_ID INTEGER NOT NULL,
        TEACHER_ID INTEGER NOT NULL,
CONSTRAINT UNIQ_SUBJECTID_TEACHERID UNIQUE (SUBJECT_ID, TEACHER_ID));

/* Table: TEACHERS, Owner: SYSDBA */
CREATE TABLE TEACHERS (ID INTEGER NOT NULL,
        NAME VARCHAR(255),
PRIMARY KEY (ID));

/* Table: WEEKDAYS, Owner: SYSDBA */
CREATE TABLE WEEKDAYS (ID INTEGER NOT NULL,
        NAME VARCHAR(64) NOT NULL,
        ORDER_NUMBER INTEGER NOT NULL,
PRIMARY KEY (ID),
UNIQUE (ORDER_NUMBER));

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_1 FOREIGN KEY (LESSON_ID) REFERENCES LESSONS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_2 FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_3 FOREIGN KEY (AUDIENCE_ID) REFERENCES AUDIENCES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_4 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_5 FOREIGN KEY (TYPE_ID) REFERENCES LESSON_TYPES (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_6 FOREIGN KEY (WEEKDAY_ID) REFERENCES WEEKDAYS (ID);

ALTER TABLE SCHED_ITEMS ADD CONSTRAINT FK_SCHED_ITEMS_7 FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_GROUP ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (ID);

ALTER TABLE SUBJECT_TEACHER ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);

ALTER TABLE SUBJECT_TEACHER ADD FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS (ID);
SET TERM ^ ;

/* Triggers only will work for SQL triggers */
CREATE TRIGGER AUDIENCES_AUTOINC_ID FOR AUDIENCES 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (AUDIENCES_GEN, 1);
END ^

CREATE TRIGGER GROUPS_AUTOINC_ID FOR GROUPS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (GROUPS_GEN, 1);
END ^

CREATE TRIGGER LESSONS_AUTOINC_ID FOR LESSONS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSONS_GEN, 1);
END ^

CREATE TRIGGER LESSON_TYPES_AUTOINC_ID FOR LESSON_TYPES 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (LESSON_TYPES_GEN, 1);
END ^

CREATE TRIGGER SCHED_ITEMS_AUTOINC_ID FOR SCHED_ITEMS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(SCHED_ITEMS_GEN, 1);
END ^

CREATE TRIGGER SUBJECT_AUTOINC_ID FOR SUBJECTS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id(subjects_gen, 1);
END ^

CREATE TRIGGER TEACHERS_AUTOINC_ID FOR TEACHERS 
ACTIVE BEFORE INSERT POSITION 1 
AS 
BEGIN 
    if (new.id is null ) then
    new.id = gen_id (TEACHERS_GEN, 1);
END ^


SET TERM ; ^
COMMIT WORK;

INSERT INTO AUDIENCES (ID,NAME) values (1,'D549a');
INSERT INTO AUDIENCES (ID,NAME) values (2,'D732');
INSERT INTO AUDIENCES (ID,NAME) values (3,'D547');
INSERT INTO AUDIENCES (ID,NAME) values (4,'D548');
INSERT INTO AUDIENCES (ID,NAME) values (5,'D549');
INSERT INTO AUDIENCES (ID,NAME) values (6,'D743');
INSERT INTO AUDIENCES (ID,NAME) values (7,'D412/542');
INSERT INTO AUDIENCES (ID,NAME) values (8,'D945');
INSERT INTO AUDIENCES (ID,NAME) values (9,'D741');
INSERT INTO AUDIENCES (ID,NAME) values (10,'D654/752');
INSERT INTO AUDIENCES (ID,NAME) values (11,'D818');
INSERT INTO AUDIENCES (ID,NAME) values (12,'D738');
INSERT INTO AUDIENCES (ID,NAME) values (13,'D733a');
INSERT INTO AUDIENCES (ID,NAME) values (14,'S');
INSERT INTO AUDIENCES (ID,NAME) values (15,'D949');
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (1,'понедельник',0);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (2,'вторник',1);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (3,'среда',2);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (4,'четверг',3);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (5,'пятница',4);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (6,'суббота',5);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (7,'воскресенье',6);
INSERT INTO GROUPS (ID,NAME) values (1,'Б8203а');
INSERT INTO GROUPS (ID,NAME) values (2,'Б8203б');
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (1,'1 пара',1);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (2,'2 пара',2);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (3,'3 пара',3);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (4,'4 пара',4);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (5,'5 пара',5);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (6,'6 пара',6);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (7,'7 пара',7);
INSERT INTO LESSON_TYPES (ID,NAME) values (1,'ПЗ');
INSERT INTO LESSON_TYPES (ID,NAME) values (2,'Л');
INSERT INTO LESSON_TYPES (ID,NAME) values (3,'ЛР');
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (1,1,2,2,1,1,2,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (2,2,1,3,1,NULL,1,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (3,2,1,4,1,NULL,1,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (4,2,1,15,1,NULL,1,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (5,3,3,1,1,2,3,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (6,4,3,1,1,2,3,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (7,1,9,13,1,6,3,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (8,1,4,6,1,9,1,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (9,3,6,7,1,3,1,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (10,2,3,13,1,2,3,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (11,4,6,7,1,3,2,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (12,3,11,9,1,7,1,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (13,5,7,14,1,NULL,1,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (14,4,11,9,1,7,2,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (15,5,7,14,1,NULL,1,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (16,2,2,8,1,1,1,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (18,3,4,7,1,4,2,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (19,4,3,12,1,8,2,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (20,5,9,10,1,5,2,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (21,1,10,5,1,8,3,4);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (22,2,10,5,1,8,3,4);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (23,3,10,11,1,8,2,4);
INSERT INTO SUBJECTS (ID,NAME) values (1,'Иностранный язык');
INSERT INTO SUBJECTS (ID,NAME) values (2,'Дискретная математика и математическая логика');
INSERT INTO SUBJECTS (ID,NAME) values (3,'Архитектура компьютеров');
INSERT INTO SUBJECTS (ID,NAME) values (4,'Математический анализ');
INSERT INTO SUBJECTS (ID,NAME) values (5,'Основы современных образовательных технологий');
INSERT INTO SUBJECTS (ID,NAME) values (6,'Обыкновенные дифференциальные уравнения');
INSERT INTO SUBJECTS (ID,NAME) values (7,'Элективные курсы по физической культуре');
INSERT INTO SUBJECTS (ID,NAME) values (9,'Численные методы');
INSERT INTO SUBJECTS (ID,NAME) values (10,'Базы данных');
INSERT INTO SUBJECTS (ID,NAME) values (11,'Теория вероятностей и математическая статистика');
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (1,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (1,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (2,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (2,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (3,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (3,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (4,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (4,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (5,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (5,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (6,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (6,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (7,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (7,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (9,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (9,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (10,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (10,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (11,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (11,2);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (2,1);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (3,2);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (3,8);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (4,4);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (4,9);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (5,10);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (6,3);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (9,5);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (9,6);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (10,8);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (11,7);
INSERT INTO TEACHERS (ID,NAME) values (1,'Василенко Н.Ю.');
INSERT INTO TEACHERS (ID,NAME) values (2,'Баранов А.А.');
INSERT INTO TEACHERS (ID,NAME) values (3,'Шепелева Р.П.');
INSERT INTO TEACHERS (ID,NAME) values (4,'Клевчихин Ю.А.');
INSERT INTO TEACHERS (ID,NAME) values (5,'Колобов А.Г.');
INSERT INTO TEACHERS (ID,NAME) values (6,'Кузнецова Н.В.');
INSERT INTO TEACHERS (ID,NAME) values (7,'Лиховидов В.Н.');
INSERT INTO TEACHERS (ID,NAME) values (8,'Кленин А.С.');
INSERT INTO TEACHERS (ID,NAME) values (9,'Ефремов Е.Л.');
INSERT INTO TEACHERS (ID,NAME) values (10,'Колосова В.Е.');
INSERT INTO TEACHERS (ID,NAME) values (11,'Веремеева Ирина Феликсовна');
INSERT INTO AUDIENCES (ID,NAME) values (1,'D549a');
INSERT INTO AUDIENCES (ID,NAME) values (2,'D732');
INSERT INTO AUDIENCES (ID,NAME) values (3,'D547');
INSERT INTO AUDIENCES (ID,NAME) values (4,'D548');
INSERT INTO AUDIENCES (ID,NAME) values (5,'D549');
INSERT INTO AUDIENCES (ID,NAME) values (6,'D743');
INSERT INTO AUDIENCES (ID,NAME) values (7,'D412/542');
INSERT INTO AUDIENCES (ID,NAME) values (8,'D945');
INSERT INTO AUDIENCES (ID,NAME) values (9,'D741');
INSERT INTO AUDIENCES (ID,NAME) values (10,'D654/752');
INSERT INTO AUDIENCES (ID,NAME) values (11,'D818');
INSERT INTO AUDIENCES (ID,NAME) values (12,'D738');
INSERT INTO AUDIENCES (ID,NAME) values (13,'D733a');
INSERT INTO AUDIENCES (ID,NAME) values (14,'S');
INSERT INTO AUDIENCES (ID,NAME) values (15,'D949');
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (1,'понедельник',0);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (2,'вторник',1);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (3,'среда',2);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (4,'четверг',3);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (5,'пятница',4);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (6,'суббота',5);
INSERT INTO WEEKDAYS (ID,NAME,ORDER_NUMBER) values (7,'воскресенье',6);
INSERT INTO GROUPS (ID,NAME) values (1,'Б8203а');
INSERT INTO GROUPS (ID,NAME) values (2,'Б8203б');
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (1,'1 пара',1);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (2,'2 пара',2);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (3,'3 пара',3);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (4,'4 пара',4);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (5,'5 пара',5);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (6,'6 пара',6);
INSERT INTO LESSONS (ID,NAME,ORDER_NUMBER) values (7,'7 пара',7);
INSERT INTO LESSON_TYPES (ID,NAME) values (1,'ПЗ');
INSERT INTO LESSON_TYPES (ID,NAME) values (2,'Л');
INSERT INTO LESSON_TYPES (ID,NAME) values (3,'ЛР');
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (1,1,2,2,1,1,2,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (2,2,1,3,1,NULL,1,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (3,2,1,4,1,NULL,1,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (4,2,1,15,1,NULL,1,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (5,3,3,1,1,2,3,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (6,4,3,1,1,2,3,1);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (7,1,9,13,1,6,3,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (8,1,4,6,1,9,1,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (9,3,6,7,1,3,1,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (10,2,3,13,1,2,3,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (11,4,6,7,1,3,2,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (12,3,11,9,1,7,1,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (13,5,7,14,1,NULL,1,2);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (14,4,11,9,1,7,2,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (15,5,7,14,1,NULL,1,5);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (16,2,2,8,1,1,1,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (18,3,4,7,1,4,2,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (19,4,3,12,1,8,2,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (20,5,9,10,1,5,2,3);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (21,1,10,5,1,8,3,4);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (22,2,10,5,1,8,3,4);
INSERT INTO SCHED_ITEMS (ID,LESSON_ID,SUBJECT_ID,AUDIENCE_ID,GROUP_ID,TEACHER_ID,TYPE_ID,WEEKDAY_ID) values (23,3,10,11,1,8,2,4);
INSERT INTO SUBJECTS (ID,NAME) values (1,'Иностранный язык');
INSERT INTO SUBJECTS (ID,NAME) values (2,'Дискретная математика и математическая логика');
INSERT INTO SUBJECTS (ID,NAME) values (3,'Архитектура компьютеров');
INSERT INTO SUBJECTS (ID,NAME) values (4,'Математический анализ');
INSERT INTO SUBJECTS (ID,NAME) values (5,'Основы современных образовательных технологий');
INSERT INTO SUBJECTS (ID,NAME) values (6,'Обыкновенные дифференциальные уравнения');
INSERT INTO SUBJECTS (ID,NAME) values (7,'Элективные курсы по физической культуре');
INSERT INTO SUBJECTS (ID,NAME) values (9,'Численные методы');
INSERT INTO SUBJECTS (ID,NAME) values (10,'Базы данных');
INSERT INTO SUBJECTS (ID,NAME) values (11,'Теория вероятностей и математическая статистика');
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (1,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (1,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (2,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (2,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (3,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (3,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (4,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (4,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (5,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (5,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (6,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (6,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (7,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (7,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (9,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (9,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (10,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (10,2);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (11,1);
INSERT INTO SUBJECT_GROUP (SUBJECT_ID,GROUP_ID) values (11,2);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (2,1);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (3,2);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (3,8);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (4,4);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (4,9);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (5,10);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (6,3);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (9,5);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (9,6);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (10,8);
INSERT INTO SUBJECT_TEACHER (SUBJECT_ID,TEACHER_ID) values (11,7);
INSERT INTO TEACHERS (ID,NAME) values (1,'Василенко Н.Ю.');
INSERT INTO TEACHERS (ID,NAME) values (2,'Баранов А.А.');
INSERT INTO TEACHERS (ID,NAME) values (3,'Шепелева Р.П.');
INSERT INTO TEACHERS (ID,NAME) values (4,'Клевчихин Ю.А.');
INSERT INTO TEACHERS (ID,NAME) values (5,'Колобов А.Г.');
INSERT INTO TEACHERS (ID,NAME) values (6,'Кузнецова Н.В.');
INSERT INTO TEACHERS (ID,NAME) values (7,'Лиховидов В.Н.');
INSERT INTO TEACHERS (ID,NAME) values (8,'Кленин А.С.');
INSERT INTO TEACHERS (ID,NAME) values (9,'Ефремов Е.Л.');
INSERT INTO TEACHERS (ID,NAME) values (10,'Колосова В.Е.');
INSERT INTO TEACHERS (ID,NAME) values (11,'Веремеева Ирина Феликсовна');
INSERT INTO AUDIENCES (ID,NAME) values (1,'D549a');
INSERT INTO AUDIENCES (ID,NAME) values (2,'D732');
INSERT INTO AUDIENCES (ID,NAME) values (3,'D547');
INSERT INTO AUDIENCES (ID,NAME) values (4,'D548');
INSERT INTO AUDIENCES (ID,NAME) values (5,'D549');
INSERT INTO AUDIENCES (ID,NAME) values (6,'D743');
INSERT INTO AUDIENCES (ID,NAME) values (7,'D412/542');
INSERT INTO AUDIENCES (ID,NAME) 